openapi: 3.0.0
info:
  title: Get Items in Custom Carousel
  version: 1.0.0
servers:
  - url: /api
paths:
  /blogs:
    get:
      summary: Return a list of blogs for the carousel
      responses:
        '200':
          description: A list of blogs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlogList'
  /categories:
    post:
      summary: Create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '201':
          description: Category created successfully
        '400':
          description: Invalid request payload
components:
  schemas:
    Blog:
      type: object
      properties:
        title:
          type: string
          description: The title of the blog
        image:
          type: string
          format: url
          description: The URL of the blog image
        link:
          type: string
          format: url
          description: The URL of the blog link
    BlogList:
      type: array
      items:
        $ref: '#/components/schemas/Blog'
    Category:
      type: object
      properties:
        title:
          type: string
          description: The title of the category
